name: CI
run-name: Build shared library
on: [push]
jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
      - run: |
          cd src
          make libcomputelib.so