name: CI
run-name: Build shared library
on: [push]
jobs:
  build:
    strategy:
        matrix:
          os: ['self-hosted']

    runs-on: ${{ matrix.os }}
    steps:
      - uses: Jimver/cuda-toolkit@v0.2.16
        id: cuda-toolkit
        with:
          cuda: '12.2.0'

      - run: nvidia-smi
      - run: nvcc --version
      - run: make libcomputelib.so
        working-directory: src